### ISSUE TITLE
Dual params corresponding to implied ps model?

### ISSUE THREAD

**Issue by jaredhuling** [ngreifer/optweight#1]
Is it possible to extract the dual parameters, i.e. \lambda^\dagger from Theorem 1 [here](https://academic.oup.com/biomet/article/107/1/93/5602475)

**Comment by ngreifer** [comment]
Yes! If you use `optweight()`, the `duals` component of the output object contains the dual variable(s) for each covariate, but these have been processed so that they are all positive and that duals for each level of a categorical variable are combined to represent a single dual for that variable. The output of `optweight.fit()`, though, contains the raw duals in its `duals` component. In theory, these could be used in the formula, but it might not be so straightforward because the sum of the weights is constrained to be `n` in `optweight`, not 1 like in W&Z. I think it will be challenging to extract propensity scores from the duals, if that is your intention. The problem in W&Z also seems to concern half of the ATE weights, so make sure your estimand corresponds to theirs if you want to replicate their results.

**Comment by jaredhuling** [comment]
Thanks! My intention is to be able to obtain weights (and not necessarily the PS's themselves) for out-of-sample observations, which from your comment seems potentially tricky

**Comment by ngreifer** [comment]
That's a cool idea! Yeah, it would be hard to do that from the `optweight` output. The duals here are mostly for diagnosing hard-to-balance covariates rather than using them directly in predictions. It would be easy to program it yourself though to get the duals in the right format. You're probably aware of [Zhao (2019)](https://projecteuclid.org/euclid.aos/1547197245), which might have some promise in this regard.

**Comment by jaredhuling** [comment]
Thanks!
